apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: coderba/demo:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080