spring:
  application:
    name: test

app:
  config:
    message: TY Tech 2019
    feature-enabled: false

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env