spring:
  application:
    name: test
  datasource:
#    url: jdbc:postgresql://localhost:5432/test_db
    url: jdbc:postgresql://10.96.155.40:5432/test_db
    username: test_user
    password: test_pass
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

app:
  config:
    message: adesso

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env
